{{- $port := .Values.bytebase.option.port -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.servicePrefix }}{{ .Release.Name }}{{ .Values.serviceSuffix }}"
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    {{- include "bytebase.labels" . | nindent 4}}
spec:
  type: ClusterIP
  selector:
    app: {{ template "bytebase.option.name" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ $port }}

